import pandas as pd
series = pd.Series([1,7,2,8,5])
print(series)
series = pd.Series([1,7,2,8,5], index = ["a","b","c","d","e"])
print(series)
print(series[2])
print(series["c"])
data = pd.DataFrame([1,2,3,4,5])
print(data)
data = pd.DataFrame({'Name':['Tom','Jack','Steve','Ricky','Sam','Will','Root'],
                     'Age':[28,34,29,42,17,17,45]})
print(data.head(10))
data = pd.DataFrame({'Name':['Tom','Jack','Steve','Ricky','Sam','Will','Root'],
                     'Age':[28,34,29,42,17,17,45]}, index=['c1','c2','c3','c4','c5','c6','c7'])
data.head(10)
print(data['Age'])
print(data.loc['c4','Age'])
print(data.iloc[3,0])
names = pd.DataFrame({'Name':['Tom','Jack','Steve','Ricky','Sam','Will','Root']})
ages = pd.DataFrame({'Age':[28,34,29,42,17,17,45]})
names2 =pd.DataFrame({'Name':['Joe','Pope','Buttler','Ben','James','Cook']})
print(pd.concat([names,names2]))
print(data[data['Age']<=18][['Name']])
print(data[data['Age']>40])
print(data)
print(data.loc['c2','Name'])
print(data.iloc[1,0])